# Generated by Django 2.2.7 on 2019-11-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=0, max_digits=5)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
